version: '3.8'

services:
  jenkins:
    image:  jenkins
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - webnet

  nexus:
    image:  docker.io/lxgaming/nexus3
    container_name: nexus3
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081" # nexus ui
      - "8082:8082" # for nexus-docker-hosted access
    networks:
      - webnet
    
  caddy:
    image:  docker.io/library/caddy
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data 
      - caddy_config:/config
    ports:
      - "8083:80"
      - "44300:443"
    networks:
      - webnet
networks:
  webnet:

volumes:
  jenkins_home:
  nexus-data:
  caddy_data:
  caddy_config: