version: '3.8'

services:
  jenkins:
    privileged: true
    image:  jenkins
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins-nexus

  nexus:
    image:  docker.io/lxgaming/nexus3
    container_name: nexus3
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081" # nexus ui
      - "8082:8082" # for nexus-docker-hosted access
    networks:
      - jenkins-nexus
    
      
networks:
  jenkins-nexus:

volumes:
  jenkins_home:
  nexus-data:
