services:
  jenkins:
    image: jenkins
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.orbstack/config/docker.json:/etc/docker/daemon.json
      - trivy_cache:/var/jenkins_home/.cache/trivy
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - dev
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

networks:
  dev:

volumes:
  jenkins_home:
  trivy_cache:
